const soliloquies = [
  {
    id: 1,
    title: "The Moral Crossroads",
    act: "Act 1, Scene 7",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Castle, Inverness",
    emotionalState: "Conflicted, Tormented",
    triggerWarnings: ["Violence", "Moral Anguish", "Murder"],
    soundscape: {
      ambientSounds: ["Castle Winds", "Flickering Fire"],
      recommendedMusic: "Contemplative Orchestral Score"
    },
    original: [
      "If it were done when 'tis done, then 'twere well",
      "It were done quickly: if the assassination",
      "Could trammel up the consequence, and catch",
      "With his surcease success; that but this blow",
      "Might be the be-all and the end-all here,",
      "But here, upon this bank and shoal of time,",
      "We'd jump the life to come. But in these cases",
      "We still have judgment here; that we but teach",
      "Bloody instructions, which, being taught, return",
      "To plague the inventor: this even-handed justice",
      "Commends the ingredients of our poison'd chalice",
      "To our own lips. He's here in double trust;",
      "First, as I am his kinsman and his subject,",
      "Strong both against the deed; then, as his host,",
      "Who should against his murderer shut the door,",
      "Not bear the knife myself. Besides, this Duncan",
      "Hath borne his faculties so meek, hath been",
      "So clear in his great office, that his virtues",
      "Will plead like angels, trumpet-tongued, against",
      "The deep damnation of his taking-off;",
      "And pity, like a naked new-born babe,",
      "Striding the blast, or heaven's cherubim, horsed",
      "Upon the sightless couriers of the air,",
      "Shall blow the horrid deed in every eye,",
      "That tears shall drown the wind. I have no spur",
      "To prick the sides of my intent, but only",
      "Vaulting ambition, which o'erleaps itself",
      "And falls on the other."
    ],
    academic: [
      "If the deed could be completed without consequences, it would be wise to act swiftly.",
      "If the assassination could contain all ramifications and achieve success through Duncan's death,",
      "If this single strike could be the ultimate resolution in this mortal realm,",
      "Here on this brief span of earthly existence,",
      "We would risk eternal damnation. However, in such matters,",
      "We face earthly judgment; we merely instruct others in violence,",
      "Which, once learned, returns to destroy the teacher.",
      "This impartial justice serves the poison we have prepared",
      "Back to our own consumption. Duncan is here under double protection:",
      "First, as my relative and king, both relationships forbid this act;",
      "Second, as my guest, I should protect him from murderers,",
      "Not wield the weapon myself. Furthermore, Duncan",
      "Has exercised his power with such gentleness and integrity",
      "In his noble position, that his moral excellence",
      "Will testify like divine messengers against",
      "The profound evil of his assassination.",
      "Compassion, like an innocent newborn",
      "Riding the storm, or heavenly angels mounted",
      "On invisible winds,",
      "Will expose this terrible crime to all observers,",
      "Until tears overwhelm the tempest. I lack motivation",
      "To drive my purpose forward, possessing only",
      "Excessive ambition, which overreaches its bounds",
      "And destroys itself."
    ],
    brainrot: [
      "if i just stab him and it’s DONE? like fr? say less.",
      "if offing this dude ends the drama permanently??? i’m in.",
      "one lil stabby stab and the whole situation disappears??? godspeed.",
      "on this crusty lil timeline of a life we got goin on rn,",
      "i’d risk hell, fr. but nah, the universe always clockin.",
      "earth got rules. like moral IRS. always collectin.",
      "teach violence once and suddenly you’re the syllabus. ok??",
      "justice really out here like ‘drink your own poison, bestie.’",
      "and duncan? man trusts me twice over like a damn fool.",
      "like bro i’m his cousin AND his employee??? be serious.",
      "also he’s literally sleeping under my roof rn???",
      "i’m supposed to protect the guy, not go full psycho mode.",
      "and to top it off, man’s a literal angel fr fr.",
      "he’s been so humble and pure it’s disgusting.",
      "his good guy energy boutta be LOUD from the heavens.",
      "even pity gonna show up like a newborn baby on a wind gust.",
      "straight up baby cherubs in the groupchat like 🚨he did WHAT???",
      "airborne angel delivery of CANCEL MACBETH, airing tonight.",
      "everyone and their mom gonna be CRYING when they find out.",
      "and me? i got NO excuse. no motive. no grindset.",
      "just raw, uncut ambition with no parental controls.",
      "this ego tryna speedrun kinghood and tripped on its own shoelace."
    ],

    psychologicalInsight: "Macbeth is performing a cost-benefit analysis of regicide while his conscience wages war against his ambition. He recognizes the moral, practical, and spiritual consequences of murder, yet cannot abandon his desire for power. This internal debate reveals a man still capable of moral reasoning, making his eventual choice more tragic.",
    difficulty: "Advanced",
    keywords: ["moral conflict", "consequences", "ambition", "justice", "hospitality"],
    artStyles: [
      { name: "Caravaggio Chiaroscuro", url: "example_caravaggio.jpg" },
      { name: "Romantic Sublime", url: "example_romantic.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Divine Right of Kings",
      socialNorms: "Sacred Bonds of Hospitality and Kinship",
      historicalFigures: ["King Duncan", "Medieval Scottish Nobility"]
    },
    performanceIntensity: 7,
    quizQuestions: [
      {
        question: "What does Macbeth mean by 'even-handed justice'?",
        options: [
          "Fair legal proceedings",
          "Divine punishment",
          "The principle that violence teaches violence and returns to harm the perpetrator",
          "Equal treatment of all subjects"
        ],
        correctAnswer: 2
      }
    ]
  },
  {
    id: 2,
    title: "Hallucination of the Dagger",
    act: "Act 2, Scene 1",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Castle, Inverness",
    emotionalState: "Anxious, Hallucinatory, Determined",
    triggerWarnings: ["Violence", "Psychological Distress", "Hallucinations"],
    soundscape: {
      ambientSounds: ["Castle Winds", "Distant Owl Hoots", "Echoing Footsteps"],
      recommendedMusic: "Tense Orchestral Score"
    },
    original: [
      "Is this a dagger which I see before me,",
      "The handle toward my hand? Come, let me clutch thee.",
      "I have thee not, and yet I see thee still.",
      "Art thou not, fatal vision, sensible",
      "To feeling as to sight? or art thou but",
      "A dagger of the mind, a false creation,",
      "Proceeding from the heat-oppressed brain?",
      "I see thee yet, in form as palpable",
      "As this which now I draw.",
      "Thou marshall'st me the way that I was going;",
      "And such an instrument I was to use.",
      "Mine eyes are made the fools o' the other senses,",
      "Or else worth all the rest; I see thee still,",
      "And on thy blade and dudgeon gouts of blood,",
      "Which was not so before. There's no such thing:",
      "It is the bloody business which informs",
      "Thus to mine eyes. Now o'er the one halfworld",
      "Nature seems dead, and wicked dreams abuse",
      "The curtain'd sleep; witchcraft celebrates",
      "Pale Hecate's offerings, and wither'd murder,",
      "Alarum'd by his sentinel, the wolf,",
      "Whose howl's his watch, thus with his stealthy pace,",
      "With Tarquin's ravishing strides, towards his design",
      "Moves like a ghost. Thou sure and firm-set earth,",
      "Hear not my steps, which way they walk, for fear",
      "Thy very stones prate of my whereabout,",
      "And take the present horror from the time,",
      "Which now suits with it. Whiles I threat, he lives:",
      "Words to the heat of deeds too cold breath gives.",
      "[A bell rings]",
      "I go, and it is done; the bell invites me.",
      "Hear it not, Duncan; for it is a knell",
      "That summons thee to heaven or to hell."
    ],
    academic: [
      "Is this a dagger I perceive before me,",
      "With its handle positioned toward my grasp? Allow me to seize you.",
      "I cannot physically possess you, yet I continue to perceive you.",
      "Are you not, deadly apparition, tangible",
      "To touch as well as sight? Or are you merely",
      "A mental construct, a psychological fabrication",
      "Emerging from my fevered consciousness?",
      "I continue to observe you, as substantial in appearance",
      "As this actual weapon I now unsheath.",
      "You guide me toward my predetermined path,",
      "You represent the very tool I intended to employ.",
      "Either my vision deceives my other faculties,",
      "Or surpasses them all in reliability; I observe you continuously,",
      "With droplets of blood upon your blade and hilt,",
      "Which were absent previously. This apparition does not exist:",
      "It is my murderous intention that creates",
      "This visual manifestation. Now across half the world",
      "Nature appears lifeless, and evil dreams disturb",
      "Sleep behind drawn curtains; supernatural forces honor",
      "The pale goddess Hecate's rituals, and personified murder,",
      "Alerted by his guardian, the wolf,",
      "Whose howl serves as his timekeeper, moves with stealthy progression,",
      "With predatory strides like the rapist Tarquin, toward his objective",
      "Like a specter. You solid and stable earth,",
      "Do not hear my footsteps or their direction, lest",
      "Your very stones reveal my location",
      "And disturb this moment of horror",
      "Which perfectly accompanies my deed. While I make threats, Duncan lives:",
      "Words provide insufficient heat compared to action's warmth.",
      "[A bell sounds]",
      "I proceed, and the deed is accomplished; the bell summons me.",
      "Do not hear it, Duncan; it is a death knell",
      "That calls you to paradise or damnation."
    ],
    brainrot: [
      "yo is that a knife or am i tweaking rn",
      "the handle’s like right there. is it flirting?? lemme grab that",
      "nope. not real. still seeing it tho. love that for me.",
      "hello? murder-vision? can i touch you or nah?",
      "are you real or just vibes??",
      "ok it’s giving ‘fake weapon my brain made up to cope’",
      "mind goin ✨ overheating processor noises ✨",
      "still there. still lookin real af.",
      "looks just like the murder utensil i brought for tonight’s event.",
      "not you leading me to the crime scene like a psychic gps.",
      "this the exact blade i was boutta use too. rude.",
      "either my eyes are wildin or they’re the only ones clocked in rn.",
      "yep. still seeing it. no notes.",
      "wait— is that BLOOD? that was not in the last update.",
      "ok hallucination.exe just downloaded gore dlc",
      "nah this ain’t a knife. this is guilt cosplayin as a weapon.",
      "my brain out here doing crime fanfic visuals.",
      "half the world’s dead asleep and i’m beefing with air rn.",
      "dreams corrupted. nightmares up. mood: cursed.",
      "witches vibin. Hecate clocked in. murder’s doing a runway walk.",
      "the wolf just howled like ‘showtime bitches’",
      "murder out here tiptoeing in his tarquin-era boots.",
      "sneakin like a ghost. no footsteps. just menace.",
      "yo earth? babe? don’t snitch. don’t echo me.",
      "don’t let the rocks start gossiping or i’m done.",
      "don’t ruin my horror aesthetic, okay?",
      "as long as i’m talking, he’s still breathing.",
      "words are useless rn. action’s the main character.",
      "*ding ding*",
      "that’s my murder alarm. time to go be insane.",
      "shhh duncan don’t hear it. it’s your heaven-or-hell ringtone."
    ],

    psychologicalInsight: "This soliloquy captures the psychological moment when reality and hallucination blur, representing Macbeth's complete mental surrender to his murderous intent. The dagger symbolizes his guilt manifesting before the crime is even committed, showing how his conscience is already being consumed by his ambition.",
    difficulty: "Hard",
    keywords: ["hallucination", "guilt", "murder", "psychological break", "supernatural"],
    artStyles: [
      { name: "Renaissance Painting", url: "example_renaissance.jpg" },
      { name: "Modern Abstract", url: "example_abstract.jpg" },
      { name: "Gothic Horror", url: "example_gothic.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Scottish Monarchy Under Threat",
      socialNorms: "Supernatural Beliefs and Witchcraft",
      historicalFigures: ["King Duncan", "Hecate", "Tarquin"]
    },
    performanceIntensity: 9,
    quizQuestions: [
      {
        question: "What does the dagger symbolize?",
        options: [
          "A real weapon",
          "Macbeth's guilt and psychological breakdown",
          "A gift from Lady Macbeth",
          "Divine intervention"
        ],
        correctAnswer: 1
      }
    ]
  },
  {
    id: 3,
    title: "Plotting Banquo's Murder",
    act: "Act 3, Scene 1",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Royal Chambers",
    emotionalState: "Paranoid, Calculating, Ruthless",
    triggerWarnings: ["Violence", "Paranoia", "Political Manipulation"],
    soundscape: {
      ambientSounds: ["Echoing Footsteps", "Distant Whispers", "Crown Jewels Clinking"],
      recommendedMusic: "Suspenseful Chamber Music"
    },
    original: [
      "To be thus is nothing;",
      "But to be safely thus.—Our fears in Banquo",
      "Stick deep; and in his royalty of nature",
      "Reigns that which would be fear'd: 'tis much he dares;",
      "And, to that dauntless temper of his mind,",
      "He hath a wisdom that doth guide his valour",
      "To act in safety. There is none but he",
      "Whose being I do fear: and, under him,",
      "My Genius is rebuked; as, it is said,",
      "Mark Antony's was by Caesar. He chid the sisters",
      "When first they put the name of king upon me,",
      "And bade them speak to him: then prophet-like",
      "They hail'd him father to a line of kings:",
      "Upon my head they placed a fruitless crown,",
      "And put a barren sceptre in my gripe,",
      "Thence to be wrench'd with an unlineal hand,",
      "No son of mine succeeding. If 't be so,",
      "For Banquo's issue have I filed my mind;",
      "For them the gracious Duncan have I murder'd;",
      "Put rancours in the vessel of my peace",
      "Only for them; and mine eternal jewel",
      "Given to the common enemy of man,",
      "To make them kings, the seed of Banquo kings!",
      "Rather than so, come fate into the list,",
      "And champion me to the utterance!"
    ],
    academic: [
      "To possess the crown means nothing",
      "Unless one can maintain it securely. Our anxieties regarding Banquo",
      "Penetrate deeply; within his noble character",
      "Exists qualities that inspire fear: he possesses great courage,",
      "And combined with his fearless disposition,",
      "He possesses wisdom that directs his bravery",
      "Toward prudent action. No one else exists",
      "Whose presence I fear: in his company,",
      "My spirit feels diminished, as reportedly",
      "Mark Antony's was in Caesar's presence. He rebuked the witches",
      "When they first proclaimed me king,",
      "And demanded they address him: then like prophets",
      "They proclaimed him ancestor to a dynasty of kings.",
      "Upon my head they placed a childless crown,",
      "And placed an inheritance-less scepter in my grasp,",
      "Destined to be seized by non-hereditary hands,",
      "With no son of mine as successor. If this prophecy proves accurate,",
      "I have corrupted my soul for Banquo's descendants;",
      "For their benefit I have murdered the virtuous Duncan,",
      "Introduced hatred into my peaceful existence",
      "Solely for their advantage; I have surrendered my immortal soul",
      "To humanity's universal enemy,",
      "To establish them as royalty, Banquo's lineage as kings!",
      "Rather than accept this outcome, let destiny enter combat",
      "And fight for me to the death!"
    ],
    brainrot: [
      "being king means nothing if i’m not king in peace, tf",
      "banquo lives rent-free in my brain and i hate it here",
      "man got natural main character energy and it’s terrifying",
      "he’s brave af. like??? sit down bro.",
      "dude’s fearless and not even dumb about it. worst combo.",
      "he’s smart *and* bold?? jail immediately.",
      "no one else gives me the ick like this man does",
      "when he’s around i feel like a dollar store prophecy",
      "it’s giving ‘mark antony vs caesar’ but make it insecure",
      "he straight-up roasted the witches for hyping me up",
      "then made them give him lore too like a true menace",
      "and they were like ‘lol ur kids are the future kings btw’",
      "they dropped a crown on my head with a timer on it",
      "and handed me a scepter that’s basically leased not owned",
      "some random bloodline gonna yoink it the moment i blink",
      "i don’t even got kids. not one heir. it’s over.",
      "so i killed duncan... for *banquo’s* legacy?? be ffr.",
      "i mentally uninstalled my conscience for *his* bloodline",
      "threw rage into my vibe jar and labeled it ‘for the banquos’",
      "gave my eternal soul to satan like it was a black friday deal",
      "just so some dudes named banquo jr. can play royal dress up",
      "lol no. absolutely not. fate get over here rn",
      "1v1 me in the arena. winner takes the throne."
    ],

    psychologicalInsight: "Macbeth has transformed from a conflicted murderer into a calculating tyrant. His paranoia has become systematic and strategic. He no longer wrestles with conscience but with logistics. The crown has not brought him peace but has created new enemies in his mind, showing how power corrupts by generating endless insecurity.",
    difficulty: "Advanced",
    keywords: ["paranoia", "power", "political strategy", "succession", "tyranny"],
    artStyles: [
      { name: "Baroque Dramatic", url: "example_baroque.jpg" },
      { name: "Expressionist", url: "example_expressionist.jpg" },
      { name: "Political Satire", url: "example_political.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Succession Struggles in Medieval Scotland",
      socialNorms: "Hereditary Monarchy and Bloodline Politics",
      historicalFigures: ["Banquo", "The Witches", "Mark Antony", "Caesar"]
    },
    performanceIntensity: 8,
    quizQuestions: [
      {
        question: "Why does Macbeth fear Banquo specifically?",
        options: [
          "Banquo knows about the murder",
          "The witches prophesied Banquo's sons would be kings",
          "Banquo is planning a rebellion",
          "Banquo is more popular with the people"
        ],
        correctAnswer: 1
      }
    ]
  },
  {
    id: 4,
    title: "Tomorrow and Tomorrow",
    act: "Act 5, Scene 5",
    originalAuthor: "William Shakespeare",
    location: "Dunsinane Castle",
    emotionalState: "Nihilistic, Exhausted, Despairing",
    triggerWarnings: ["Existential Crisis", "Depression", "Death"],
    soundscape: {
      ambientSounds: ["Distant Battle Sounds", "Wind Through Ruins", "Silence"],
      recommendedMusic: "Melancholic Minimalist Score"
    },
    original: [
      "She should have died hereafter;",
      "There would have been a time for such a word.",
      "To-morrow, and to-morrow, and to-morrow,",
      "Creeps in this petty pace from day to day",
      "To the last syllable of recorded time,",
      "And all our yesterdays have lighted fools",
      "The way to dusty death. Out, out, brief candle!",
      "Life's but a walking shadow, a poor player",
      "That struts and frets his hour upon the stage",
      "And then is heard no more: it is a tale",
      "Told by an idiot, full of sound and fury,",
      "Signifying nothing."
    ],
    academic: [
      "She should have died at a future time;",
      "There would have been an appropriate moment for such news.",
      "Each successive day, and day, and day",
      "Advances at this insignificant rate from one day to the next",
      "Until the final moment of documented history,",
      "And all our past days have illuminated foolish people",
      "The path to inevitable death. Extinguish yourself, brief flame!",
      "Life is merely an insubstantial shadow, an inadequate actor",
      "Who poses and worries during his brief time on stage",
      "And then is never heard from again: existence is a narrative",
      "Recounted by a madman, filled with noise and violence,",
      "Representing absolutely nothing meaningful."
    ],
    brainrot: [
      "she could’ve died later tbh, timing was mid",
      "wasn't even ready for this news rn. not the vibe.",
      "tomorrow and tomorrow and tomorrow, bro shut UP",
      "days just keep dragging like a crusty Netflix show that won’t end",
      "every second crawls till the world just hits delete",
      "and all our yesterdays? just clown parades to the grave, fr",
      "blow out the candle. light’s dead. vibes gone.",
      "life? shadow. man-shaped glitch. npc energy.",
      "just some dude fake-acting for a sec then vanishing like 💨",
      "existence? bad improv. no plot. no audience.",
      "it's giving ‘yelled by a lunatic in an alleyway’",
      "loud for no reason. zero meaning. literally nothing."
    ],
    psychologicalInsight: "This represents Macbeth's complete philosophical collapse. Having lost everything through his pursuit of power, he now sees existence itself as meaningless. The man who once agonized over moral choices now views life as an incoherent performance, suggesting that his moral corruption has led to existential nihilism.",
    difficulty: "Advanced",
    keywords: ["nihilism", "existential crisis", "meaninglessness", "death", "time"],
    artStyles: [
      { name: "Existentialist", url: "example_existentialist.jpg" },
      { name: "Abstract Expressionist", url: "example_abstract_expressionist.jpg" },
      { name: "Minimalist", url: "example_minimalist.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Fall of Macbeth's Tyrannical Reign",
      socialNorms: "Concepts of Honor and Tragic Downfall",
      historicalFigures: ["Lady Macbeth", "Malcolm", "Macduff"]
    },
    performanceIntensity: 10,
    quizQuestions: [
      {
        question: "What does the 'brief candle' metaphor represent?",
        options: [
          "Lady Macbeth's death",
          "The shortness and fragility of human life",
          "The end of his reign",
          "His lost innocence"
        ],
        correctAnswer: 1
      }
    ]
  }
];

export default soliloquies;
