const soliloquies = [
  {
    id: 1,
    title: "The Moral Crossroads",
    act: "Act 1, Scene 7",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Castle, Inverness",
    emotionalState: "Conflicted, Tormented",
    triggerWarnings: ["Violence", "Moral Anguish", "Murder"],
    soundscape: {
      ambientSounds: ["Castle Winds", "Flickering Fire"],
      recommendedMusic: "Contemplative Orchestral Score"
    },
    original: [
      "If it were done when 'tis done, then 'twere well",
      "It were done quickly: if the assassination",
      "Could trammel up the consequence, and catch",
      "With his surcease success; that but this blow",
      "Might be the be-all and the end-all here,",
      "But here, upon this bank and shoal of time,",
      "We'd jump the life to come. But in these cases",
      "We still have judgment here; that we but teach",
      "Bloody instructions, which, being taught, return",
      "To plague the inventor: this even-handed justice",
      "Commends the ingredients of our poison'd chalice",
      "To our own lips. He's here in double trust;",
      "First, as I am his kinsman and his subject,",
      "Strong both against the deed; then, as his host,",
      "Who should against his murderer shut the door,",
      "Not bear the knife myself. Besides, this Duncan",
      "Hath borne his faculties so meek, hath been",
      "So clear in his great office, that his virtues",
      "Will plead like angels, trumpet-tongued, against",
      "The deep damnation of his taking-off;",
      "And pity, like a naked new-born babe,",
      "Striding the blast, or heaven's cherubim, horsed",
      "Upon the sightless couriers of the air,",
      "Shall blow the horrid deed in every eye,",
      "That tears shall drown the wind. I have no spur",
      "To prick the sides of my intent, but only",
      "Vaulting ambition, which o'erleaps itself",
      "And falls on the other."
    ],
    academic: [
      "If the deed could be completed without consequences, it would be wise to act swiftly.",
      "If the assassination could contain all ramifications and achieve success through Duncan's death,",
      "If this single strike could be the ultimate resolution in this mortal realm,",
      "Here on this brief span of earthly existence,",
      "We would risk eternal damnation. However, in such matters,",
      "We face earthly judgment; we merely instruct others in violence,",
      "Which, once learned, returns to destroy the teacher.",
      "This impartial justice serves the poison we have prepared",
      "Back to our own consumption. Duncan is here under double protection:",
      "First, as my relative and king, both relationships forbid this act;",
      "Second, as my guest, I should protect him from murderers,",
      "Not wield the weapon myself. Furthermore, Duncan",
      "Has exercised his power with such gentleness and integrity",
      "In his noble position, that his moral excellence",
      "Will testify like divine messengers against",
      "The profound evil of his assassination.",
      "Compassion, like an innocent newborn",
      "Riding the storm, or heavenly angels mounted",
      "On invisible winds,",
      "Will expose this terrible crime to all observers,",
      "Until tears overwhelm the tempest. I lack motivation",
      "To drive my purpose forward, possessing only",
      "Excessive ambition, which overreaches its bounds",
      "And destroys itself."
    ],
    brainrot: [
      "If I could commit murder with zero consequences, that would be ideal",
      "If killing the king could somehow stop all the drama that follows",
      "If one stab could solve everything permanently in this life",
      "Here in our short time on earth",
      "We would risk going to hell. But in situations like this",
      "We still get judged on earth; we just teach people how to be violent",
      "And then that violence comes back to hurt us",
      "Karma serves us the same poison we made",
      "Duncan trusts me twice over:",
      "First, I'm his family and his subject, both reasons not to kill him",
      "Second, I'm his host, so I should protect him from killers",
      "Not be the killer myself. Also, Duncan",
      "Has been such a gentle and honest king",
      "That his goodness will speak against",
      "The absolute evil of murdering him",
      "And pity, like a helpless baby",
      "Or angels on invisible horses",
      "Will make everyone see this horrible crime",
      "Until the whole world cries. I have no real reason",
      "To push myself toward this goal, just",
      "Crazy ambition that reaches too high",
      "And falls flat on its face."
    ],
    psychologicalInsight: "Macbeth is performing a cost-benefit analysis of regicide while his conscience wages war against his ambition. He recognizes the moral, practical, and spiritual consequences of murder, yet cannot abandon his desire for power. This internal debate reveals a man still capable of moral reasoning, making his eventual choice more tragic.",
    difficulty: "Advanced",
    keywords: ["moral conflict", "consequences", "ambition", "justice", "hospitality"],
    artStyles: [
      { name: "Caravaggio Chiaroscuro", url: "example_caravaggio.jpg" },
      { name: "Romantic Sublime", url: "example_romantic.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Divine Right of Kings",
      socialNorms: "Sacred Bonds of Hospitality and Kinship",
      historicalFigures: ["King Duncan", "Medieval Scottish Nobility"]
    },
    performanceIntensity: 7,
    quizQuestions: [
      {
        question: "What does Macbeth mean by 'even-handed justice'?",
        options: [
          "Fair legal proceedings",
          "Divine punishment",
          "The principle that violence teaches violence and returns to harm the perpetrator",
          "Equal treatment of all subjects"
        ],
        correctAnswer: 2
      }
    ]
  },
  {
    id: 2,
    title: "Hallucination of the Dagger",
    act: "Act 2, Scene 1",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Castle, Inverness",
    emotionalState: "Anxious, Hallucinatory, Determined",
    triggerWarnings: ["Violence", "Psychological Distress", "Hallucinations"],
    soundscape: {
      ambientSounds: ["Castle Winds", "Distant Owl Hoots", "Echoing Footsteps"],
      recommendedMusic: "Tense Orchestral Score"
    },
    original: [
      "Is this a dagger which I see before me,",
      "The handle toward my hand? Come, let me clutch thee.",
      "I have thee not, and yet I see thee still.",
      "Art thou not, fatal vision, sensible",
      "To feeling as to sight? or art thou but",
      "A dagger of the mind, a false creation,",
      "Proceeding from the heat-oppressed brain?",
      "I see thee yet, in form as palpable",
      "As this which now I draw.",
      "Thou marshall'st me the way that I was going;",
      "And such an instrument I was to use.",
      "Mine eyes are made the fools o' the other senses,",
      "Or else worth all the rest; I see thee still,",
      "And on thy blade and dudgeon gouts of blood,",
      "Which was not so before. There's no such thing:",
      "It is the bloody business which informs",
      "Thus to mine eyes. Now o'er the one halfworld",
      "Nature seems dead, and wicked dreams abuse",
      "The curtain'd sleep; witchcraft celebrates",
      "Pale Hecate's offerings, and wither'd murder,",
      "Alarum'd by his sentinel, the wolf,",
      "Whose howl's his watch, thus with his stealthy pace,",
      "With Tarquin's ravishing strides, towards his design",
      "Moves like a ghost. Thou sure and firm-set earth,",
      "Hear not my steps, which way they walk, for fear",
      "Thy very stones prate of my whereabout,",
      "And take the present horror from the time,",
      "Which now suits with it. Whiles I threat, he lives:",
      "Words to the heat of deeds too cold breath gives.",
      "[A bell rings]",
      "I go, and it is done; the bell invites me.",
      "Hear it not, Duncan; for it is a knell",
      "That summons thee to heaven or to hell."
    ],
    academic: [
      "Is this a dagger I perceive before me,",
      "With its handle positioned toward my grasp? Allow me to seize you.",
      "I cannot physically possess you, yet I continue to perceive you.",
      "Are you not, deadly apparition, tangible",
      "To touch as well as sight? Or are you merely",
      "A mental construct, a psychological fabrication",
      "Emerging from my fevered consciousness?",
      "I continue to observe you, as substantial in appearance",
      "As this actual weapon I now unsheath.",
      "You guide me toward my predetermined path,",
      "You represent the very tool I intended to employ.",
      "Either my vision deceives my other faculties,",
      "Or surpasses them all in reliability; I observe you continuously,",
      "With droplets of blood upon your blade and hilt,",
      "Which were absent previously. This apparition does not exist:",
      "It is my murderous intention that creates",
      "This visual manifestation. Now across half the world",
      "Nature appears lifeless, and evil dreams disturb",
      "Sleep behind drawn curtains; supernatural forces honor",
      "The pale goddess Hecate's rituals, and personified murder,",
      "Alerted by his guardian, the wolf,",
      "Whose howl serves as his timekeeper, moves with stealthy progression,",
      "With predatory strides like the rapist Tarquin, toward his objective",
      "Like a specter. You solid and stable earth,",
      "Do not hear my footsteps or their direction, lest",
      "Your very stones reveal my location",
      "And disturb this moment of horror",
      "Which perfectly accompanies my deed. While I make threats, Duncan lives:",
      "Words provide insufficient heat compared to action's warmth.",
      "[A bell sounds]",
      "I proceed, and the deed is accomplished; the bell summons me.",
      "Do not hear it, Duncan; it is a death knell",
      "That calls you to paradise or damnation."
    ],
    brainrot: [
      "Is that a knife floating in front of me",
      "With the handle pointing at my hand? Let me grab it.",
      "I can't actually touch it but I can still see it.",
      "Are you real enough to feel",
      "Or just something I can see? Or are you just",
      "My brain creating a fake knife",
      "Because my mind is overheating from stress?",
      "I can still see you, looking as real",
      "As this actual knife I'm pulling out.",
      "You're showing me the way I was already planning to go",
      "You're exactly the weapon I was going to use anyway.",
      "Either my eyes are lying to my other senses",
      "Or they're the only ones telling the truth; I still see you",
      "And now there's blood drops on your blade and handle",
      "Which weren't there before. This thing isn't real:",
      "It's my murder plans that are making",
      "My eyes see things. Now across half the world",
      "Everything seems dead, and evil dreams mess with",
      "People sleeping behind curtains; witches are celebrating",
      "Their pale goddess Hecate's ceremonies, and murder itself,",
      "Warned by its guard dog, the wolf,",
      "Whose howl tells time, moves sneakily",
      "Like a rapist stalking his victim, toward his target",
      "Like a ghost. You solid ground,",
      "Don't listen to my footsteps or where I'm going, because",
      "Even the stones might snitch on my location",
      "And ruin this perfect moment of horror",
      "That matches what I'm about to do. While I talk, Duncan's alive:",
      "Words are cold compared to the heat of actually doing something.",
      "[Bell rings]",
      "I'm going now, and it's happening; the bell is calling me.",
      "Don't hear it, Duncan; it's a death bell",
      "That's calling you to heaven or hell."
    ],
    psychologicalInsight: "This soliloquy captures the psychological moment when reality and hallucination blur, representing Macbeth's complete mental surrender to his murderous intent. The dagger symbolizes his guilt manifesting before the crime is even committed, showing how his conscience is already being consumed by his ambition.",
    difficulty: "Hard",
    keywords: ["hallucination", "guilt", "murder", "psychological break", "supernatural"],
    artStyles: [
      { name: "Renaissance Painting", url: "example_renaissance.jpg" },
      { name: "Modern Abstract", url: "example_abstract.jpg" },
      { name: "Gothic Horror", url: "example_gothic.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Scottish Monarchy Under Threat",
      socialNorms: "Supernatural Beliefs and Witchcraft",
      historicalFigures: ["King Duncan", "Hecate", "Tarquin"]
    },
    performanceIntensity: 9,
    quizQuestions: [
      {
        question: "What does the dagger symbolize?",
        options: [
          "A real weapon",
          "Macbeth's guilt and psychological breakdown",
          "A gift from Lady Macbeth",
          "Divine intervention"
        ],
        correctAnswer: 1
      }
    ]
  },
  {
    id: 3,
    title: "Plotting Banquo's Murder",
    act: "Act 3, Scene 1",
    originalAuthor: "William Shakespeare",
    location: "Macbeth's Royal Chambers",
    emotionalState: "Paranoid, Calculating, Ruthless",
    triggerWarnings: ["Violence", "Paranoia", "Political Manipulation"],
    soundscape: {
      ambientSounds: ["Echoing Footsteps", "Distant Whispers", "Crown Jewels Clinking"],
      recommendedMusic: "Suspenseful Chamber Music"
    },
    original: [
      "To be thus is nothing;",
      "But to be safely thus.—Our fears in Banquo",
      "Stick deep; and in his royalty of nature",
      "Reigns that which would be fear'd: 'tis much he dares;",
      "And, to that dauntless temper of his mind,",
      "He hath a wisdom that doth guide his valour",
      "To act in safety. There is none but he",
      "Whose being I do fear: and, under him,",
      "My Genius is rebuked; as, it is said,",
      "Mark Antony's was by Caesar. He chid the sisters",
      "When first they put the name of king upon me,",
      "And bade them speak to him: then prophet-like",
      "They hail'd him father to a line of kings:",
      "Upon my head they placed a fruitless crown,",
      "And put a barren sceptre in my gripe,",
      "Thence to be wrench'd with an unlineal hand,",
      "No son of mine succeeding. If 't be so,",
      "For Banquo's issue have I filed my mind;",
      "For them the gracious Duncan have I murder'd;",
      "Put rancours in the vessel of my peace",
      "Only for them; and mine eternal jewel",
      "Given to the common enemy of man,",
      "To make them kings, the seed of Banquo kings!",
      "Rather than so, come fate into the list,",
      "And champion me to the utterance!"
    ],
    academic: [
      "To possess the crown means nothing",
      "Unless one can maintain it securely. Our anxieties regarding Banquo",
      "Penetrate deeply; within his noble character",
      "Exists qualities that inspire fear: he possesses great courage,",
      "And combined with his fearless disposition,",
      "He possesses wisdom that directs his bravery",
      "Toward prudent action. No one else exists",
      "Whose presence I fear: in his company,",
      "My spirit feels diminished, as reportedly",
      "Mark Antony's was in Caesar's presence. He rebuked the witches",
      "When they first proclaimed me king,",
      "And demanded they address him: then like prophets",
      "They proclaimed him ancestor to a dynasty of kings.",
      "Upon my head they placed a childless crown,",
      "And placed an inheritance-less scepter in my grasp,",
      "Destined to be seized by non-hereditary hands,",
      "With no son of mine as successor. If this prophecy proves accurate,",
      "I have corrupted my soul for Banquo's descendants;",
      "For their benefit I have murdered the virtuous Duncan,",
      "Introduced hatred into my peaceful existence",
      "Solely for their advantage; I have surrendered my immortal soul",
      "To humanity's universal enemy,",
      "To establish them as royalty, Banquo's lineage as kings!",
      "Rather than accept this outcome, let destiny enter combat",
      "And fight for me to the death!"
    ],
    brainrot: [
      "Being king is pointless",
      "Unless you can stay king safely. My worries about Banquo",
      "Go really deep; he's got this natural royal quality",
      "That's actually scary: he's super brave,",
      "And with his fearless personality,",
      "He's smart enough to use his courage",
      "In safe ways. There's nobody else",
      "That I'm actually afraid of: when I'm around him,",
      "I feel inferior, like they say",
      "Mark Antony felt around Caesar. He told off the witches",
      "When they first called me king,",
      "And made them talk to him too: then like fortune tellers",
      "They said he'd be the father of a bunch of future kings.",
      "They put a crown on my head that will never pass to my kids,",
      "And gave me a scepter that won't stay in my family,",
      "It'll get taken by someone not related to me,",
      "Since I don't have a son to inherit it. If that's really going to happen,",
      "I've ruined my soul just so Banquo's kids can be king;",
      "I killed the good king Duncan just for them,",
      "I've filled my peaceful life with anger and hatred",
      "All for their benefit; I've sold my soul",
      "To the devil",
      "Just to make them royalty, to make Banquo's family the royal line!",
      "Instead of letting that happen, let fate come fight me",
      "And we'll battle to the death!"
    ],
    psychologicalInsight: "Macbeth has transformed from a conflicted murderer into a calculating tyrant. His paranoia has become systematic and strategic. He no longer wrestles with conscience but with logistics. The crown has not brought him peace but has created new enemies in his mind, showing how power corrupts by generating endless insecurity.",
    difficulty: "Advanced",
    keywords: ["paranoia", "power", "political strategy", "succession", "tyranny"],
    artStyles: [
      { name: "Baroque Dramatic", url: "example_baroque.jpg" },
      { name: "Expressionist", url: "example_expressionist.jpg" },
      { name: "Political Satire", url: "example_political.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Succession Struggles in Medieval Scotland",
      socialNorms: "Hereditary Monarchy and Bloodline Politics",
      historicalFigures: ["Banquo", "The Witches", "Mark Antony", "Caesar"]
    },
    performanceIntensity: 8,
    quizQuestions: [
      {
        question: "Why does Macbeth fear Banquo specifically?",
        options: [
          "Banquo knows about the murder",
          "The witches prophesied Banquo's sons would be kings",
          "Banquo is planning a rebellion",
          "Banquo is more popular with the people"
        ],
        correctAnswer: 1
      }
    ]
  },
  {
    id: 4,
    title: "Tomorrow and Tomorrow",
    act: "Act 5, Scene 5",
    originalAuthor: "William Shakespeare",
    location: "Dunsinane Castle",
    emotionalState: "Nihilistic, Exhausted, Despairing",
    triggerWarnings: ["Existential Crisis", "Depression", "Death"],
    soundscape: {
      ambientSounds: ["Distant Battle Sounds", "Wind Through Ruins", "Silence"],
      recommendedMusic: "Melancholic Minimalist Score"
    },
    original: [
      "She should have died hereafter;",
      "There would have been a time for such a word.",
      "To-morrow, and to-morrow, and to-morrow,",
      "Creeps in this petty pace from day to day",
      "To the last syllable of recorded time,",
      "And all our yesterdays have lighted fools",
      "The way to dusty death. Out, out, brief candle!",
      "Life's but a walking shadow, a poor player",
      "That struts and frets his hour upon the stage",
      "And then is heard no more: it is a tale",
      "Told by an idiot, full of sound and fury,",
      "Signifying nothing."
    ],
    academic: [
      "She should have died at a future time;",
      "There would have been an appropriate moment for such news.",
      "Each successive day, and day, and day",
      "Advances at this insignificant rate from one day to the next",
      "Until the final moment of documented history,",
      "And all our past days have illuminated foolish people",
      "The path to inevitable death. Extinguish yourself, brief flame!",
      "Life is merely an insubstantial shadow, an inadequate actor",
      "Who poses and worries during his brief time on stage",
      "And then is never heard from again: existence is a narrative",
      "Recounted by a madman, filled with noise and violence,",
      "Representing absolutely nothing meaningful."
    ],
    brainrot: [
      "She should have died later;",
      "There would have been a better time to hear about this.",
      "Tomorrow, and tomorrow, and tomorrow",
      "Crawls along slowly day after day",
      "Until the very end of recorded time,",
      "And all our past days have just shown stupid people",
      "The way to death. Go out, you brief candle!",
      "Life is just a walking shadow, a bad actor",
      "Who shows off and worries for his short time on stage",
      "And then nobody remembers him: life is a story",
      "Told by a crazy person, full of loud noises and anger,",
      "That doesn't mean anything at all."
    ],
    psychologicalInsight: "This represents Macbeth's complete philosophical collapse. Having lost everything through his pursuit of power, he now sees existence itself as meaningless. The man who once agonized over moral choices now views life as an incoherent performance, suggesting that his moral corruption has led to existential nihilism.",
    difficulty: "Advanced",
    keywords: ["nihilism", "existential crisis", "meaninglessness", "death", "time"],
    artStyles: [
      { name: "Existentialist", url: "example_existentialist.jpg" },
      { name: "Abstract Expressionist", url: "example_abstract_expressionist.jpg" },
      { name: "Minimalist", url: "example_minimalist.jpg" }
    ],
    historicalContext: {
      politicalBackground: "Fall of Macbeth's Tyrannical Reign",
      socialNorms: "Concepts of Honor and Tragic Downfall",
      historicalFigures: ["Lady Macbeth", "Malcolm", "Macduff"]
    },
    performanceIntensity: 10,
    quizQuestions: [
      {
        question: "What does the 'brief candle' metaphor represent?",
        options: [
          "Lady Macbeth's death",
          "The shortness and fragility of human life",
          "The end of his reign",
          "His lost innocence"
        ],
        correctAnswer: 1
      }
    ]
  }
];

export default soliloquies;
